# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookstore.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookstore.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='books')),
        ),
    ]
